### ISSUE TITLE
How should the CSV be formatted?

### ISSUE THREAD

**Issue by amanuel1995** [mklawiter/WebexControlHubScripts#1]

**Comment by mklawiter** [comment]
Hi amanuel1995!  The CSV uses the same format as the CSV export from Control Hub.
**Notes:**  
- Keep the rows of users that should be deleted and REMOVE USERS who should NOT be deleted
- Do not delete the header line, or the first user to delete will be skipped
- Very little validation is done of the input file.  Deleting fields will break this script.

Honestly the only field that you need to make sure is included is that the third field of each row is the email address.  

**Example:** 
First Name,Last Name,Display Name,User ID/Email (Required),User Status, ....
John,Doe,John Doe,john@doe.com,Not Verified, ...
Jane,Doe,Jane Doe,"jane@doe.com",, ...
,,,doe@doe.com,, ...

**Comment by amanuel1995** [comment]
Got it thanks. I changed the script since my export was from another record and I only had the emails.
